
spring:
  datasource:
    url: jdbc:mysql://150.158.167.162:3306/taro?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
    username: root
    password: lmzs1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  config:
    activate:
      on-profile:
        - prod
server:
  port: 8082


#mybatis ??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  ip : localhost